import JSZip from "jszip";
import {
  buildInputLine,
  buildPasteSnippet,
  buildStandaloneDocument,
  extractPreambleLines,
  slugFromPrompt,
} from "@/lib/figure-export";
import type { DocumentFit, OutputType } from "@/lib/openrouter";

export interface ExportBundleInput {
  latex: string;
  prompt: string;
  documentFit: DocumentFit;
  outputType: OutputType | null;
}

export async function buildFigureZip(input: ExportBundleInput): Promise<Blob> {
  const slug = slugFromPrompt(input.prompt);
  const standalone = buildStandaloneDocument(input.latex);
  const snippet = buildPasteSnippet(input.latex, input.documentFit, input.outputType);
  const preamble = extractPreambleLines(input.latex);
  const inputLine = buildInputLine(slug);

  const readme = `teXlab figure export
=====================

Files:
- figure.tex      Standalone document (compiles on its own)
- snippet.tex     Paste into your paper (figure/table environment)
- preamble.tex    Packages to add to your main document preamble
- ${slug}.tex     Same as snippet — use with \\input{}

Quick start:
1. Copy lines from preamble.tex into your main .tex preamble (if needed).
2. Paste snippet.tex inside \\begin{document} ... \\end{document}
   OR save snippet as figures/${slug}.tex and add:
   ${inputLine}

Generated by teXlab — publication-ready figures that fit your column.
`;

  const zip = new JSZip();
  zip.file("figure.tex", standalone);
  zip.file("snippet.tex", snippet);
  zip.file("preamble.tex", preamble);
  zip.file(`${slug}.tex`, snippet);
  zip.file("README.txt", readme);

  return zip.generateAsync({ type: "blob", compression: "DEFLATE" });
}

async function blobToBase64(blob: Blob): Promise<string> {
  const buffer = await blob.arrayBuffer();
  const bytes = new Uint8Array(buffer);
  let binary = "";
  const chunkSize = 0x8000;
  for (let i = 0; i < bytes.length; i += chunkSize) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunkSize));
  }
  return btoa(binary);
}

function textToBase64(text: string): string {
  return btoa(unescape(encodeURIComponent(text)));
}

/** POST directly to Overleaf with embedded base64 — works on localhost and production. */
function submitOverleafForm(fields: Record<string, string>): void {
  const form = document.createElement("form");
  form.method = "POST";
  form.action = "https://www.overleaf.com/docs";
  form.target = "_blank";
  form.rel = "noopener noreferrer";

  for (const [name, value] of Object.entries(fields)) {
    const input = document.createElement("input");
    input.type = "hidden";
    input.name = name;
    input.value = value;
    form.appendChild(input);
  }

  document.body.appendChild(form);
  form.submit();
  form.remove();
}

/**
 * Open a zip project in Overleaf via base64 data URL (Overleaf API docs).
 * Falls back to a single figure.tex if the zip payload is too large.
 */
export async function openInOverleaf(input: ExportBundleInput): Promise<void> {
  const standalone = buildStandaloneDocument(input.latex);

  try {
    const zipBlob = await buildFigureZip(input);
    // Overleaf accepts ~few MB; keep zip path for multi-file projects when small.
    if (zipBlob.size < 1_500_000) {
      const zipBase64 = await blobToBase64(zipBlob);
      submitOverleafForm({
        snip_uri: `data:application/zip;base64,${zipBase64}`,
        engine: "pdflatex",
        main_document: "figure.tex",
      });
      return;
    }
  } catch (error) {
    console.warn("Zip export failed, falling back to single .tex:", error);
  }

  const texBase64 = textToBase64(standalone);
  submitOverleafForm({
    snip_uri: `data:application/x-tex;base64,${texBase64}`,
    engine: "pdflatex",
  });
}

export async function downloadFigureZip(input: ExportBundleInput): Promise<void> {
  const blob = await buildFigureZip(input);
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = "texlab-figure.zip";
  anchor.click();
  URL.revokeObjectURL(url);
}
